#!/bin/sh
#
# Author: LUC SORIGNET
# Automatically adds ticket number and branch description as title to every commit message.
# branch name should respect INEO Style : E99999-FEATURE-TRI
#
# Save this file in your local git repo at:
#     .git/hooks/prepare-commit-msg
#
# (no *.sh file extension)
# Then, run:
#     chmod +x prepare-commit-msg

NAME=$(git branch | grep '*' | sed 's/* //')
TICKET=$(echo $NAME | egrep -o '[0-9]{5}')
TITLE=$(echo $NAME| egrep -o '\-[A-Za-z0-9_]+\-'|sed 's/-//g' | sed 's/_/ /g')

echo "NAME: $NAME"
echo "TICKET: $TICKET"
echo "TITLE: $TITLE"

COMMIT_MESSAGE=`cat $1`


echo "refs #$TICKET : $TITLE" > $1

echo "#=========================================================">>$1
echo "#CHECK LIST">>$1
echo "#[1] Avant de commiter vérifiez et tester tout vos fichier!">>$1
echo "#[2] Si la cible est sous linux verifiez les retours chariots avec dos2unix notament pour les scripts pythons">>$1
echo "#[3] Verifiez si la solution compile ">>$1
echo "#[4] Vérifiez la documentation et la convention de codage">>$1
echo "#========================================================">>$1

echo "$COMMIT_MESSAGE" >>$1
