set nocompatible      " Nécessaire
filetype off          " Nécessaire

" Ajout de Vundle au runtime path et initialisation
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" On indique à Vundle de s'auto-gérer :)
Plugin 'VundleVim/Vundle.vim'  " Nécessaire

"
" C'est ici que vous allez placer la liste des plugins que Vundle doit gérer
"
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'airblade/vim-gitgutter'
Plugin 'tomasr/molokai'
Plugin 'fmoralesc/molokayo'
Plugin 'scrooloose/nerdtree'
call vundle#end()            " Nécessaire
filetype plugin indent on    " Nécessaire
scriptencoding utf-8
set encoding=utf-8

" Nerd Tree config
" autocmd vimenter * NERDTree
nmap <F6> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

"Airline config
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'


set laststatus=2
set noshowmode
" Enable syntax highlighting
colo molokayo
syntax on

" Better command-line completion
set wildmenu

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch
set visualbell
" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler
" Enable use of the mouse for all modes
set mouse=a
" Display line numbers on the left
set number
" Indentation settings for using 4 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=4
set softtabstop=4
set expandtab

set list
set listchars=tab:»·,trail:·,nbsp:⎵ ",eol:¶
" Remove trailing space at save
autocmd FileType c,cpp,java,php,py autocmd BufWritePre <buffer> %s/\s\+$//e
