
#Platform detector
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   # enable color support of ls and also add handy aliases
	if [ -x /usr/bin/dircolors ]; then
	    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	    alias ls='ls --color=auto'
	    #alias dir='dir --color=auto'
	    #alias vdir='vdir --color=auto'
	    alias grep='grep --color=auto'
	    alias fgrep='fgrep --color=auto'
	    alias egrep='egrep --color=auto'
	fi
else
	#UNIX
	alias ls='ls -CFG'
	alias grep='grep -G'
	alias fgrep='fgrep -G'
	alias egrep='egrep -G'
fi


alias l="ls"
alias ll="ls -l"
alias la="ls -al"

alias clrhistory="rm ~/.bash_history; history -c ; clear;"
alias bashrcvi="vi ~/.bashrc; source ~/.bashrc"

